# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from diffs.compat import get_jsonfield_class
JSONField = get_jsonfield_class()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created', models.BooleanField()),
                ('diff', JSONField()),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('parent_object_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
        ),
    ]
